---
title: Goshen Community Contra Dancing
timezone: America/New_York
collections:
  dances:
    title: Dances
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
